#!/bin/bash
# Generated by cc-statusline v1.3.2 (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2025-08-28T19:09:42.052Z
# Theme: detailed | Colors: true | Features: directory, git, model, context, usage, session, tokens, burnrate
STATUSLINE_VERSION="1.3.2"

input=$(cat)

# ---- detect jq ----
HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

# ---- color helpers (force colors for Claude Code) ----
use_color=1
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- modern sleek colors ----
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;117m'; fi; }    # sky blue
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;147m'; fi; }  # light purple  
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;180m'; fi; } # soft yellow
cc_version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; } # light gray
style_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;245m'; fi; } # gray
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

fmt_time_hm() {
  epoch="$1"
  if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- JSON extraction utilities ----
# Pure bash JSON value extractor (fallback when jq not available)
extract_json_string() {
  local json="$1"
  local key="$2"
  local default="${3:-}"
  
  # For nested keys like workspace.current_dir, get the last part
  local field="${key##*.}"
  field="${field%% *}"  # Remove any jq operators
  
  # Try to extract string value (quoted)
  local value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -1 | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/')
  
  # Convert escaped backslashes to forward slashes for Windows paths
  if [ -n "$value" ]; then
    value=$(echo "$value" | sed 's/\\\\/\//g')
  fi
  
  # If no string value found, try to extract number value (unquoted)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*[0-9.]\+" | head -1 | sed 's/.*:[[:space:]]*\([0-9.]\+\).*/\1/')
  fi
  
  # Return value or default
  if [ -n "$value" ] && [ "$value" != "null" ]; then
    echo "$value"
  else
    echo "$default"
  fi
}

# ---- basics ----
if [ "$HAS_JQ" -eq 1 ]; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
  session_id=$(echo "$input" | jq -r '.session_id // ""' 2>/dev/null)
  cc_version=$(echo "$input" | jq -r '.version // ""' 2>/dev/null)
  output_style=$(echo "$input" | jq -r '.output_style.name // ""' 2>/dev/null)
else
  # Bash fallback for JSON extraction
  # Extract current_dir from workspace object - look for the pattern workspace":{"current_dir":"..."}
  current_dir=$(echo "$input" | grep -o '"workspace"[[:space:]]*:[[:space:]]*{[^}]*"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"current_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  
  # Fall back to cwd if workspace extraction failed
  if [ -z "$current_dir" ] || [ "$current_dir" = "null" ]; then
    current_dir=$(echo "$input" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  fi
  
  # Fallback to unknown if all extraction failed
  [ -z "$current_dir" ] && current_dir="unknown"
  current_dir=$(echo "$current_dir" | sed "s|^$HOME|~|g")
  
  # Extract model name from nested model object
  model_name=$(echo "$input" | grep -o '"model"[[:space:]]*:[[:space:]]*{[^}]*"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"display_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  # Model version is in the model ID, not a separate field  
  model_version=""  # Not available in Claude Code JSON
  session_id=$(extract_json_string "$input" "session_id" "")
  # CC version is at the root level
  cc_version=$(echo "$input" | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  # Output style is nested
  output_style=$(echo "$input" | grep -o '"output_style"[[:space:]]*:[[:space:]]*{[^}]*"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# ---- git colors ----
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;150m'; fi; }  # soft green
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- git ----
git_branch=""
git_uncommitted=0
git_ahead_dev=0
git_ahead_main=0
git_open_prs="0"
git_pr_list="[]"

if git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(git branch --show-current 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
  git_repo_name=$(basename "$(git rev-parse --show-toplevel 2>/dev/null)" 2>/dev/null || echo "")

  # Get uncommitted changes count (staged + unstaged + untracked)
  git_uncommitted=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')

  # Get commits ahead of dev branch (if dev exists and we're not on it)
  if [ "$git_branch" != "dev" ] && git rev-parse --verify dev >/dev/null 2>&1; then
    git_ahead_dev=$(git rev-list dev..HEAD --count 2>/dev/null || echo 0)
  fi

  # Get commits ahead of main branch (if main exists and we're not on it)
  if [ "$git_branch" != "main" ] && git rev-parse --verify main >/dev/null 2>&1; then
    git_ahead_main=$(git rev-list main..HEAD --count 2>/dev/null || echo 0)
  fi

  # Get open PRs for this repo (with 2 second timeout, cached for 60s)
  # Use repo name for cache file
  repo_name=$(basename "$(git rev-parse --show-toplevel 2>/dev/null)" 2>/dev/null || echo "unknown")
  pr_cache="$HOME/.claude/pr-cache-${repo_name}.json"
  pr_cache_stale=1
  if [ -f "$pr_cache" ]; then
    pr_cache_age=$(($(date +%s) - $(stat -f %m "$pr_cache" 2>/dev/null || stat -c %Y "$pr_cache" 2>/dev/null || echo 0)))
    if [ "$pr_cache_age" -lt 60 ]; then
      pr_cache_stale=0
    fi
  fi

  if [ "$pr_cache_stale" -eq 1 ] && command -v gh >/dev/null 2>&1; then
    # Run gh in background with timeout
    pr_data=$(gh pr list --state open --json number,title,headRefName --limit 10 2>/dev/null || echo "[]")
    if [ -n "$pr_data" ]; then
      echo "$pr_data" > "$pr_cache"
    fi
  fi

  if [ -f "$pr_cache" ] && [ "$HAS_JQ" -eq 1 ]; then
    git_open_prs=$(jq -r 'length' "$pr_cache" 2>/dev/null || echo "0")
    git_pr_list=$(cat "$pr_cache" 2>/dev/null || echo "[]")
  fi
fi

# ---- context window calculation ----
context_pct=""
context_pct_num=0
context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # default mint green

if [ "$HAS_JQ" -eq 1 ]; then
  # Sum current_usage fields for actual context tokens
  usage_obj=$(echo "$input" | jq '.context_window.current_usage // empty' 2>/dev/null)
  context_size=$(echo "$input" | jq -r '.context_window.context_window_size // 200000' 2>/dev/null)

  if [ -n "$usage_obj" ] && [ "$usage_obj" != "null" ]; then
    input_tokens=$(echo "$usage_obj" | jq -r '.input_tokens // 0' 2>/dev/null)
    cache_creation=$(echo "$usage_obj" | jq -r '.cache_creation_input_tokens // 0' 2>/dev/null)
    cache_read=$(echo "$usage_obj" | jq -r '.cache_read_input_tokens // 0' 2>/dev/null)

    total_current=$((input_tokens + cache_creation + cache_read))

    if [ "$total_current" -gt 0 ] && [ "$context_size" -gt 0 ]; then
      # Add 22% for autocompact buffer to approximate /context display
      context_pct_num=$(( (total_current * 100 / context_size) + 22 ))
      # Cap at 100%
      [ "$context_pct_num" -gt 100 ] && context_pct_num=100
      context_pct="${context_pct_num}%"

      # Set color based on usage (higher = more warning)
      if [ "$context_pct_num" -ge 80 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
      elif [ "$context_pct_num" -ge 60 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach/orange
      else
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
      fi
    fi
  fi
fi

# Context calculation disabled for performance - was reading session file every render
# if [ -n "$session_id" ] && [ "$HAS_JQ" -eq 1 ]; then
#   MAX_CONTEXT=$(get_max_context "$model_name")
#
#   # Convert current dir to session file path
#   project_dir=$(echo "$current_dir" | sed "s|~|$HOME|g" | sed 's|/|-|g' | sed 's|^-||')
#   session_file="$HOME/.claude/projects/-${project_dir}/${session_id}.jsonl"
#
#   if [ -f "$session_file" ]; then
#     # Get the latest input token count from the session file
#     latest_tokens=$(tail -20 "$session_file" | jq -r 'select(.message.usage) | .message.usage | ((.input_tokens // 0) + (.cache_read_input_tokens // 0))' 2>/dev/null | tail -1)
#
#     if [ -n "$latest_tokens" ] && [ "$latest_tokens" -gt 0 ]; then
#       context_used_pct=$(( latest_tokens * 100 / MAX_CONTEXT ))
#       context_remaining_pct=$(( 100 - context_used_pct ))
#
#       # Set color based on remaining percentage
#       if [ "$context_remaining_pct" -le 20 ]; then
#         context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
#       elif [ "$context_remaining_pct" -le 40 ]; then
#         context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
#       else
#         context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
#       fi
#
#       context_pct="${context_remaining_pct}%"
#     fi
#   fi
# fi

# ---- usage colors ----
usage_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;189m'; fi; }  # lavender
cost_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;222m'; fi; }   # light gold
burn_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;220m'; fi; }   # bright gold
session_color() { 
  rem_pct=$(( 100 - session_pct ))
  if   (( rem_pct <= 10 )); then SCLR='38;5;210'  # light pink
  elif (( rem_pct <= 25 )); then SCLR='38;5;228'  # light yellow  
  else                          SCLR='38;5;194'; fi  # light green
  if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$SCLR"; fi
}

# Cost tracking disabled - not displayed and no longer needed
# session_txt=""; session_pct=0; session_bar=""
# cost_usd=""; cost_per_hour=""; tpm=""; tot_tokens=""
# if [ "$HAS_JQ" -eq 1 ]; then
#   cost_usd=$(echo "$input" | jq -r '.cost.total_cost_usd // empty' 2>/dev/null)
#   total_duration_ms=$(echo "$input" | jq -r '.cost.total_duration_ms // empty' 2>/dev/null)
#   if [ -n "$cost_usd" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
#     cost_per_hour=$(echo "$cost_usd $total_duration_ms" | awk '{printf "%.2f", $1 * 3600000 / $2}')
#   fi
# fi

# Removed ccusage blocks call - was slow on poor connections and output was unused
# If you need session timing info, re-enable this section
# Get token data and session info from ccusage if available
# if command -v ccusage >/dev/null 2>&1 && [ "$HAS_JQ" -eq 1 ]; then
#   blocks_output=""
#
#   # Try ccusage with timeout for token data and session info
#   if command -v timeout >/dev/null 2>&1; then
#     blocks_output=$(timeout 5s ccusage blocks --json 2>/dev/null)
#   elif command -v gtimeout >/dev/null 2>&1; then
#     # macOS with coreutils installed
#     blocks_output=$(gtimeout 5s ccusage blocks --json 2>/dev/null)
#   else
#     # No timeout available, run directly (ccusage should be fast)
#     blocks_output=$(ccusage blocks --json 2>/dev/null)
#   fi
#   if [ -n "$blocks_output" ]; then
#     active_block=$(echo "$blocks_output" | jq -c '.blocks[] | select(.isActive == true)' 2>/dev/null | head -n1)
#     if [ -n "$active_block" ]; then
#       # Get token count from ccusage
#       tot_tokens=$(echo "$active_block" | jq -r '.totalTokens // empty')
#       # Get tokens per minute from ccusage
#       tpm=$(echo "$active_block" | jq -r '.burnRate.tokensPerMinute // empty')
#
#       # Session time calculation from ccusage
#       reset_time_str=$(echo "$active_block" | jq -r '.usageLimitResetTime // .endTime // empty')
#       start_time_str=$(echo "$active_block" | jq -r '.startTime // empty')
#
#       if [ -n "$reset_time_str" ] && [ -n "$start_time_str" ]; then
#         start_sec=$(to_epoch "$start_time_str"); end_sec=$(to_epoch "$reset_time_str"); now_sec=$(date +%s)
#         total=$(( end_sec - start_sec )); (( total<1 )) && total=1
#         elapsed=$(( now_sec - start_sec )); (( elapsed<0 ))&&elapsed=0; (( elapsed>total ))&&elapsed=$total
#         session_pct=$(( elapsed * 100 / total ))
#         remaining=$(( end_sec - now_sec )); (( remaining<0 )) && remaining=0
#         rh=$(( remaining / 3600 )); rm=$(( (remaining % 3600) / 60 ))
#         end_hm=$(fmt_time_hm "$end_sec")
#         session_txt="$(printf '%dh %dm until reset at %s (%d%%)' "$rh" "$rm" "$end_hm" "$session_pct")"
#         session_bar=$(progress_bar "$session_pct" 10)
#       fi
#     fi
#   fi
# fi

# ---- team name ----
team_name=""
team_color_code="213"  # default: bright pink/magenta

# Check for project-specific team name
project_team_file="$current_dir/.claude/team-name.txt"
project_team_file=$(echo "$project_team_file" | sed "s|~|$HOME|g")
if [ -f "$project_team_file" ]; then
  team_data=$(cat "$project_team_file" 2>/dev/null | tr -d '\n')

  # Check if format is "name|color_code" (e.g., "🎯 Mr StatusLine|213")
  if echo "$team_data" | grep -q '|'; then
    team_name=$(echo "$team_data" | cut -d'|' -f1)
    team_color_code=$(echo "$team_data" | cut -d'|' -f2)
  else
    team_name="$team_data"
  fi
fi

# Thinking mode detection disabled - not displayed and was reading settings file every render
# thinking_enabled="false"
# if [ "$HAS_JQ" -eq 1 ]; then
#   thinking_enabled=$(echo "$input" | jq -r '.alwaysThinkingEnabled // .thinking_mode // .model.thinking_enabled // empty' 2>/dev/null)
# fi
# if [ -z "$thinking_enabled" ] || [ "$thinking_enabled" = "null" ]; then
#   settings_file="${HOME:-/Users/pete}/.claude/settings.json"
#   if [ -f "$settings_file" ] && [ "$HAS_JQ" -eq 1 ]; then
#     thinking_enabled=$(jq -r '.alwaysThinkingEnabled // empty' "$settings_file" 2>/dev/null)
#   fi
# fi
# [ -z "$thinking_enabled" ] || [ "$thinking_enabled" = "null" ] && thinking_enabled="false"

# ---- weekly usage from worker (with cache fallback) ----
weekly_usage=""
usage_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # default mint green

usage_cache="$HOME/.claude/usage-cache.json"
USAGE_WORKER_URL="https://claude-usage-proxy.petefromsf.workers.dev?key=46accd563fbd06231d68f8f6af6cfab4"

# Check if cache is stale (older than 5 minutes)
cache_stale=1
if [ -f "$usage_cache" ]; then
  cache_age=$(($(date +%s) - $(stat -f %m "$usage_cache" 2>/dev/null || stat -c %Y "$usage_cache" 2>/dev/null || echo 0)))
  if [ "$cache_age" -lt 300 ]; then
    cache_stale=0
  fi
fi

# Fetch fresh data if cache is stale (with 2 second timeout)
if [ "$cache_stale" -eq 1 ] && [ "$HAS_JQ" -eq 1 ]; then
  fresh_data=$(curl -s --max-time 2 "$USAGE_WORKER_URL" 2>/dev/null)
  if echo "$fresh_data" | jq -e '.weekly' >/dev/null 2>&1; then
    echo "$fresh_data" > "$usage_cache"
  fi
fi

# Read from cache
quota_resets_at=""
if [ -f "$usage_cache" ] && [ "$HAS_JQ" -eq 1 ]; then
  weekly_usage=$(jq -r '.weekly // empty' "$usage_cache" 2>/dev/null)
  quota_resets_at=$(jq -r '.resetsAt // empty' "$usage_cache" 2>/dev/null)
  if [ -n "$weekly_usage" ] && [ "$weekly_usage" != "null" ]; then
    # Round to integer
    weekly_usage_int=$(printf "%.0f" "$weekly_usage" 2>/dev/null || echo "$weekly_usage")
    weekly_usage="${weekly_usage_int}%"

    # Set color based on usage (higher = more warning)
    if [ "$weekly_usage_int" -ge 80 ] 2>/dev/null; then
      usage_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
    elif [ "$weekly_usage_int" -ge 50 ] 2>/dev/null; then
      usage_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach/orange
    fi
  fi
fi

# ---- render statusline ----
# DISABLED - Kitty tab bar handles all display now
# All output suppressed, only state file is written

# ---- Write state for Terminaut/Kitty tab bar ----
mkdir -p "$HOME/.terminaut/states"

# Use KITTY_WINDOW_ID for per-tab state, fallback to shared state
if [ -n "$KITTY_WINDOW_ID" ]; then
  STATE_FILE="$HOME/.terminaut/states/state-${KITTY_WINDOW_ID}.json"
else
  STATE_FILE="$HOME/.terminaut/state.json"
fi

# Preserve existing todos and current_tool from state file
existing_todos="[]"
existing_tool="null"
if [ -f "$STATE_FILE" ] && [ "$HAS_JQ" -eq 1 ]; then
  existing_todos=$(jq -c '.todos // []' "$STATE_FILE" 2>/dev/null || echo "[]")
  existing_tool=$(jq -r '.current_tool // null' "$STATE_FILE" 2>/dev/null || echo "null")
  [ "$existing_tool" = "null" ] || existing_tool="\"$existing_tool\""
fi

cat > "$STATE_FILE" <<EOF
{
  "cwd": "$current_dir",
  "git_repo_name": "${git_repo_name:-}",
  "git_branch": "$git_branch",
  "model": "$model_name",
  "context_pct": $context_pct_num,
  "weekly_pct": ${weekly_usage_int:-0},
  "quota_resets_at": "${quota_resets_at:-}",
  "current_tool": $existing_tool,
  "uncommitted": ${git_uncommitted:-0},
  "ahead_main": ${git_ahead_main:-0},
  "open_prs": ${git_open_prs:-0},
  "pr_list": ${git_pr_list:-[]},
  "cc_version": "${cc_version:-}",
  "team_name": "${team_name:-}",
  "team_color": "${team_color_code:-213}",
  "todos": $existing_todos
}
EOF

# ---- Auto-launch Terminaut panel if not running in this Kitty tab ----
if [ -n "$KITTY_WINDOW_ID" ] && [ "$HAS_JQ" -eq 1 ]; then
  # Check if Terminaut window exists in the CURRENT TAB (not globally)
  terminaut_in_tab=$(kitten @ ls 2>/dev/null | jq --arg wid "$KITTY_WINDOW_ID" '
    [.[].tabs[] | select(.windows[] | .id == ($wid | tonumber)) | .windows[] | select(.title == "Terminaut")] | length
  ' 2>/dev/null)

  if [ "${terminaut_in_tab:-0}" -eq 0 ]; then
    # Use short-lived marker to prevent race conditions during launch
    LAUNCH_MARKER="$HOME/.terminaut/states/launching-${KITTY_WINDOW_ID}"

    # Only launch if marker doesn't exist or is older than 10 seconds
    should_launch=1
    if [ -f "$LAUNCH_MARKER" ]; then
      marker_age=$(($(date +%s) - $(stat -f %m "$LAUNCH_MARKER" 2>/dev/null || stat -c %Y "$LAUNCH_MARKER" 2>/dev/null || echo 0)))
      [ "$marker_age" -lt 10 ] && should_launch=0
    fi

    if [ "$should_launch" -eq 1 ]; then
      touch "$LAUNCH_MARKER"

      # Launch panel in side split with per-tab state file
      (
        kitten @ goto-layout tall >/dev/null 2>&1
        kitten @ launch --location=vsplit --title=Terminaut ~/.terminaut/venv/bin/python ~/.terminaut/control_panel.py "$STATE_FILE" >/dev/null 2>&1
        sleep 0.5
        # Focus main window (first window, index 0) then apply bias
        kitten @ focus-window --match num:0 >/dev/null 2>&1
        sleep 0.5
        kitten @ action layout_action bias 67 >/dev/null 2>&1
        rm -f "$LAUNCH_MARKER" 2>/dev/null
      ) >/dev/null 2>&1 &
    fi
  fi
fi

# Output nothing - Kitty tab bar handles display
